### ISSUE TITLE
only one pod scheduled on vNode

### ISSUE THREAD

**Issue by lenisha** [kedacore/sample-hello-world-azure-functions#5]
Followed instruction to run on VirtualNode and uses following trigger with queueLength 1
 ```
triggers:
  - type: azure-queue
    metadata:
      name: msg
      type: queueTrigger
      direction: in
      queueName: blobevents
      connection: org1_STORAGE
      queueLength: 1
```
Sending 4 messages to the queue, still shows one pod processing all messages sequentially and deployment always has desired state 1
```
 kubectl get deploy
NAME           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
trigger-keda   1         1         1            1           13m
```

It works as expected on regular Nodes, with 4 pods created ...
